[tools]
helm = "4.1.4"
jq = "1.8.1"
kubectl = "1.35.3"
minikube = "1.38.1"

#########################
# Default Configuration #
#########################
# All vars can be overridden at call time as env vars, e.g.:
#   K8SCLUSTER=my-cluster POSTGRESQL_NODES=1 mise run start

[vars]
K8SCLUSTER = "pg-test"
NAMESPACE = "pg-test"
INSTALL_PROMETHEUS = "true"
WITH_MONITORING = "true"

# https://github.com/cloudnative-pg/cloudnative-pg/tags
CNPG_VERSION = "1.29.0"

CNPG_OPERATOR_CHART_VERSION = "0.28.0" # OperatorVersion=1.29.0  # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/Chart.yaml
CNPG_CLUSTER_CHART_VERSION = "0.6.0"   # https://github.com/cloudnative-pg/charts/blob/main/charts/cluster/Chart.yaml

POSTGRESQL_INSTANCE = "postgresql-testing"
POSTGRESQL_VERSION = "18.3"
# POSTGRESQL_EXTENSION = "hypopg-hll-cron"
POSTGRESQL_DISK_SIZE = "50Gi"
POSTGRESQL_NODES = "3"
POSTGRESQL_NODE_MEM = "2Gi"
POSTGRESQL_NODE_CPU = "1000m"
# POSTGRESQL_IMAGE = "ghcr.io/wanix/postgresql:{{vars.POSTGRESQL_VERSION}}-{{vars.POSTGRESQL_EXTENSION}}"
POSTGRESQL_IMAGE = "ghcr.io/cloudnative-pg/postgresql:{{vars.POSTGRESQL_VERSION}}"

MINIKUBE = "true"
MINIKUBE_RESOURCES = "--memory 6144 --cpus 4"
STORAGE_CLASS = "manual"     # https://minikube.sigs.k8s.io/docs/drivers/
MINIKUBE_DRIVER = "podman"   # docker, podman, virtualbox, hyperkit, kvm2, parallels, vmware, ssh
MINIKUBE_NODES = "3"

GRAFANA_PORT = "8080"

###############
# Mise tasks  #
###############

[task_config]
includes = [
  "mise/tasks.d/*.toml",
]
