#####################
# Global repo tasks #
#####################
[init]
description = "Initialize the env for the repo"
run = """
#!/usr/bin/env bash
set -euo pipefail

KUBECTL_PNG_SRC="aqua:cloudnative-pg/cloudnative-pg/kubectl-cnpg"
CNPG_VERSION="${CNPG_VERSION:-{{vars.CNPG_VERSION}}}"

mise ls -c | grep -qe "${KUBECTL_PNG_SRC}\\s\\+${CNPG_VERSION}\\s\\+" \
  || mise use --env local "${KUBECTL_PNG_SRC}@${CNPG_VERSION}"
mise install
"""

[mrproper]
description = "Delete everything temporary and generated, including cluster and profile and local mise data"
depends = ["infra-delete-cluster", "infra-delete-profile"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"

GENERATED_K8S_PATH="generated/k8s/${K8SCLUSTER}.d"
GENERATED_HELM_VALUES_PATH="generated/helm-values/${K8SCLUSTER}.d"
KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

rmdir "${GENERATED_K8S_PATH}" 2>/dev/null || true
rmdir "${GENERATED_HELM_VALUES_PATH}" 2>/dev/null || true

rm -f nohup.out
rm -f mise.local.toml
rm -f "${KUBECONFIG}"
mise prune --tools -y
"""

[start]
description = "Start the infrastructure and the cluster, and port-forward Grafana if enabled"
depends_post = [
  "infra-configure",
  "infra-start",
  "cnpg-operator-update",
  "cnpg-cluster-update",
  "infra-grafana-port-forward-start",
  "infra-info"
]
run = """
#!/usr/bin/env bash
set -euo pipefail
cat << EOF
--------------------------------------------------------------------------------
        Starting the infrastructure, installing operator and cluster
--------------------------------------------------------------------------------
EOF
"""

[lsvars]
description = "List environment vars that can be used to override default configuration at call time"
run = """
#!/usr/bin/env bash
set -euo pipefail
yq -Poy '.vars' mise.toml
"""
