###############################
# Creating the infrastructure #
###############################
[infra-configure]
description = "Create configuration files and needed directories"
depends = ["init"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
NAMESPACE="${NAMESPACE:-{{vars.NAMESPACE}}}"
POSTGRESQL_INSTANCE="${POSTGRESQL_INSTANCE:-{{vars.POSTGRESQL_INSTANCE}}}"
POSTGRESQL_VERSION="${POSTGRESQL_VERSION:-{{vars.POSTGRESQL_VERSION}}}"
POSTGRESQL_NODES="${POSTGRESQL_NODES:-{{vars.POSTGRESQL_NODES}}}"
POSTGRESQL_NODE_MEM="${POSTGRESQL_NODE_MEM:-{{vars.POSTGRESQL_NODE_MEM}}}"
POSTGRESQL_NODE_CPU="${POSTGRESQL_NODE_CPU:-{{vars.POSTGRESQL_NODE_CPU}}}"
POSTGRESQL_DISK_SIZE="${POSTGRESQL_DISK_SIZE:-{{vars.POSTGRESQL_DISK_SIZE}}}"
POSTGRESQL_IMAGE="${POSTGRESQL_IMAGE:-{{vars.POSTGRESQL_IMAGE}}}"
STORAGE_CLASS="${STORAGE_CLASS:-{{vars.STORAGE_CLASS}}}"
WITH_MONITORING="${WITH_MONITORING:-{{vars.WITH_MONITORING}}}"
CNPG_OPERATOR_CHART_VERSION="${CNPG_OPERATOR_CHART_VERSION:-{{vars.CNPG_OPERATOR_CHART_VERSION}}}"
CNPG_CLUSTER_CHART_VERSION="${CNPG_CLUSTER_CHART_VERSION:-{{vars.CNPG_CLUSTER_CHART_VERSION}}}"
CNPG_VERSION="${CNPG_VERSION:-{{vars.CNPG_VERSION}}}"
MINIKUBE_DRIVER="${MINIKUBE_DRIVER:-{{vars.MINIKUBE_DRIVER}}}"
MINIKUBE_NODES="${MINIKUBE_NODES:-{{vars.MINIKUBE_NODES}}}"

MINIKUBE_PERSISTENT_PATH="${PWD}/persistentVolumesData/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
GENERATED_K8S_PATH="generated/k8s/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
GENERATED_HELM_VALUES_PATH="generated/helm-values/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
GENERATED_CFG_PATH="generated/cfg/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
KUBE_MOUNT_PATH="/tmp/hostpath_pv_data/${POSTGRESQL_INSTANCE}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"
export KUBEMOUNTPATH="$KUBE_MOUNT_PATH"
export KSNAMESPACE="$NAMESPACE"
export KSSHAREDSPACE="$MINIKUBE_PERSISTENT_PATH"
export PGVERSION="$POSTGRESQL_VERSION"
export PGINSTANCENAME="$POSTGRESQL_INSTANCE"
export PGMAINPASSWORD="${POSTGRESQL_MAIN_PASSWORD:-}"
export PGUSERNAME="${POSTGRESQL_USER:-}"
export PGUSERPASSWORD="${POSTGRESQL_PASSWORD:-}"
export PGMAINDB="${POSTGRESQL_DB:-}"
export PGDISKSIZE="$POSTGRESQL_DISK_SIZE"
export PGINSTANCESNUMBER="$POSTGRESQL_NODES"
export PGINSTANCEMEM="$POSTGRESQL_NODE_MEM"
export PGINSTANCECPU="$POSTGRESQL_NODE_CPU"
export PGSTORAGECLASS="$STORAGE_CLASS"
export PGCONTAINERIMAGE="$POSTGRESQL_IMAGE"
export PGPROMMONITORING="$WITH_MONITORING"
export PGUSERUID="$(id -u)"
export PGUSERGID="$(id -g)"

export PGPOOLERINSTANCESNUMBER="${PGPOOLERINSTANCESNUMBER:-{{vars.PGPOOLERINSTANCESNUMBER}}}"
export PGPOOLERPOOLSIZE="${PGPOOLERPOOLSIZE:-{{vars.PGPOOLERPOOLSIZE}}}"
export PGPOOLERMAXCONN="${PGPOOLERMAXCONN:-{{vars.PGPOOLERMAXCONN}}}"

echo "-- Creating configuration files and needed directories"
mkdir -p "${MINIKUBE_PERSISTENT_PATH}/postgresql" "${MINIKUBE_PERSISTENT_PATH}/psql"
mkdir -p "$GENERATED_K8S_PATH" "$GENERATED_HELM_VALUES_PATH" "$GENERATED_CFG_PATH"

cat kubernetes/cm-postgresql-client.yml.tpl     | envsubst > "${GENERATED_K8S_PATH}/cm-postgresql-client.yml"
cat kubernetes/pod-postgresql-client.yml.tpl    | envsubst > "${GENERATED_K8S_PATH}/pod-postgresql-client.yml"
cat kubernetes/pv-postgresql-client.yml.tpl     | envsubst > "${GENERATED_K8S_PATH}/pv-postgresql-client.yml"
cat kubernetes/pvc-postgresql-client.yml.tpl    | envsubst > "${GENERATED_K8S_PATH}/pvc-postgresql-client.yml"
cat kubernetes/pod-monitor-cnpg-cluster.yml.tpl | envsubst > "${GENERATED_K8S_PATH}/pod-monitor-cnpg-cluster.yml"
cat kubernetes/pv-postgresql-data.yml.tpl       | envsubst > "${GENERATED_K8S_PATH}/pv-postgresql-data.yml"

for i in $(seq -w 1 "$POSTGRESQL_NODES"); do
  mkdir -p "${MINIKUBE_PERSISTENT_PATH}/postgresql/data-node-${i}"
  chmod 777 "${MINIKUBE_PERSISTENT_PATH}/postgresql/data-node-${i}"
  export PGNODE="$i"
  cat kubernetes/pv-postgresql-data.yml.tpl | envsubst > "${GENERATED_K8S_PATH}/pv-postgresql-data-${i}.yml"
done

cat kubernetes/helm-cnpg-operator.yml.tpl         | envsubst > "${GENERATED_HELM_VALUES_PATH}/helm-cnpg-operator.yml"
cat kubernetes/helm-cnpg-cluster.yml.tpl          | envsubst > "${GENERATED_HELM_VALUES_PATH}/helm-cnpg-cluster.yml"
cat kubernetes/helm-kube-prometheus-stack.yml.tpl | envsubst > "${GENERATED_HELM_VALUES_PATH}/helm-kube-prometheus-stack.yml"
"""

[infra-start]
description = "Configure and start the full stack (minikube + monitoring + cnpg + postgresql)"
depends = ["infra-configure"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
NAMESPACE="${NAMESPACE:-{{vars.NAMESPACE}}}"
POSTGRESQL_INSTANCE="${POSTGRESQL_INSTANCE:-{{vars.POSTGRESQL_INSTANCE}}}"
POSTGRESQL_VERSION="${POSTGRESQL_VERSION:-{{vars.POSTGRESQL_VERSION}}}"
POSTGRESQL_NODES="${POSTGRESQL_NODES:-{{vars.POSTGRESQL_NODES}}}"
POSTGRESQL_IMAGE="${POSTGRESQL_IMAGE:-{{vars.POSTGRESQL_IMAGE}}}"
CNPG_OPERATOR_CHART_VERSION="${CNPG_OPERATOR_CHART_VERSION:-{{vars.CNPG_OPERATOR_CHART_VERSION}}}"
CNPG_CLUSTER_CHART_VERSION="${CNPG_CLUSTER_CHART_VERSION:-{{vars.CNPG_CLUSTER_CHART_VERSION}}}"
INSTALL_PROMETHEUS="${INSTALL_PROMETHEUS:-{{vars.INSTALL_PROMETHEUS}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"
MINIKUBE_RESOURCES="${MINIKUBE_RESOURCES:-{{vars.MINIKUBE_RESOURCES}}}"
MINIKUBE_DRIVER="${MINIKUBE_DRIVER:-{{vars.MINIKUBE_DRIVER}}}"
MINIKUBE_NODES="${MINIKUBE_NODES:-{{vars.MINIKUBE_NODES}}}"
GRAFANA_PORT="${GRAFANA_PORT:-{{vars.GRAFANA_PORT}}}"
PGPOOLERINSTANCESNUMBER="${PGPOOLERINSTANCESNUMBER:-{{vars.PGPOOLERINSTANCESNUMBER}}}"

MINIKUBE_PERSISTENT_PATH="${PWD}/persistentVolumesData/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
GENERATED_K8S_PATH="generated/k8s/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
GENERATED_HELM_VALUES_PATH="generated/helm-values/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
KUBE_MOUNT_PATH="/tmp/hostpath_pv_data/${POSTGRESQL_INSTANCE}"
KUBEVERSION="$(kubectl version --client -o json | jq -r .clientVersion.gitVersion)"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

# -- Start minikube
if [ "$MINIKUBE" = "true" ]; then
  echo "-- Starting Minikube"
  if [ "$MINIKUBE_DRIVER" = "podman" ] || [ "$MINIKUBE_DRIVER" = "docker" ]; then
    minikube config set rootless false
    minikube start -p "$K8SCLUSTER" $MINIKUBE_RESOURCES \
      --kubernetes-version="$KUBEVERSION" \
      --driver="$MINIKUBE_DRIVER" \
      --nodes "$MINIKUBE_NODES" \
      --mount --mount-string "${MINIKUBE_PERSISTENT_PATH}:${KUBE_MOUNT_PATH}"
  else
    minikube start -p "$K8SCLUSTER" $MINIKUBE_RESOURCES \
      --kubernetes-version="$KUBEVERSION" \
      --driver="$MINIKUBE_DRIVER" \
      --nodes "$MINIKUBE_NODES"
  fi
  minikube -p "$K8SCLUSTER" addons enable metrics-server
  minikube -p "$K8SCLUSTER" addons enable dashboard
  minikube -p "$K8SCLUSTER" addons enable ingress
  minikube -p "$K8SCLUSTER" addons enable volumesnapshots
fi

# -- Install monitoring
if [ "$INSTALL_PROMETHEUS" = "true" ] && [ "$MINIKUBE" = "true" ]; then
  echo "-- Install monitoring"
  kubectl get ns monitoring 2>&1 >/dev/null || kubectl create ns monitoring
  helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  helm upgrade --install prometheus-community --namespace monitoring \
    -f "${GENERATED_HELM_VALUES_PATH}/helm-kube-prometheus-stack.yml" \
    prometheus-community/kube-prometheus-stack
fi
"""

[infra-grafana-port-forward-start]
description = "Start the Grafana port-forward"
wait_for = ["infra-start"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"

INSTALL_PROMETHEUS="${INSTALL_PROMETHEUS:-{{vars.INSTALL_PROMETHEUS}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"
GRAFANA_PORT="${GRAFANA_PORT:-{{vars.GRAFANA_PORT}}}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

# -- Forward grafana
if [ "$INSTALL_PROMETHEUS" = "true" ] && [ "$MINIKUBE" = "true" ]; then
  echo "-- Waiting Grafana to be available"
  ./helpers/wait_for_pods_to_exist.sh 5 60 '  waiting pod creation' \
    -n monitoring -l app.kubernetes.io/instance=prometheus-community -l app.kubernetes.io/name=grafana
  echo "  waiting grafana availability"
  kubectl wait pod --timeout 120s --for=condition=Ready \
    -n monitoring -l app.kubernetes.io/instance=prometheus-community -l app.kubernetes.io/name=grafana
  running=$(ps -ef | grep "kubectl port-forward --address localhost -n monitoring svc/prometheus-community-grafana ${GRAFANA_PORT}:80" | grep -vc grep || true)
  if [ "$running" -eq 0 ]; then
    echo "-- Forwarding Grafana"
    nohup kubectl port-forward --address localhost -n monitoring "svc/prometheus-community-grafana" "${GRAFANA_PORT}:80" &
  fi
fi
"""

[infra-grafana-port-forward-stop]
description = "Stop the Grafana port-forward"
wait_for = ["infra-start"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"

INSTALL_PROMETHEUS="${INSTALL_PROMETHEUS:-{{vars.INSTALL_PROMETHEUS}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"
GRAFANA_PORT="${GRAFANA_PORT:-{{vars.GRAFANA_PORT}}}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

# Stop grafana port-forward
if [ "$MINIKUBE" = "true" ] && [ "$INSTALL_PROMETHEUS" = "true" ]; then
  running=$(ps -ef | grep "kubectl port-forward --address localhost -n monitoring svc/prometheus-community-grafana ${GRAFANA_PORT}:80" | grep -vc grep || true)
  if [ "$running" -gt 0 ]; then
    echo "-- Stopping Grafana port-forward"
    ps -ef \
      | grep "kubectl port-forward --address localhost -n monitoring svc/prometheus-community-grafana ${GRAFANA_PORT}:80" \
      | grep -v grep \
      | awk '{print $2}' \
      | xargs kill 2>/dev/null || true
    rm -f nohup.out
  fi
fi
"""

[infra-stop]
description = "Stop the minikube cluster and grafana port-forward"
depends = ["infra-grafana-port-forward-stop"]
alias = ["stop"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
POSTGRESQL_INSTANCE="${POSTGRESQL_INSTANCE:-{{vars.POSTGRESQL_INSTANCE}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"

MINIKUBE_PERSISTENT_PATH="${PWD}/persistentVolumesData/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

if [ "$MINIKUBE" = "true" ]; then
  echo "-- Stopping Minikube cluster"
  minikube stop -p "$K8SCLUSTER" || true
else
  echo "This operation is for minikube driver only!"
fi
"""
[infra-status-silent]
description = "check Minikube status silently, return 0 if running, something else if not"
wait_for = ["infra-start"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

if [ "$MINIKUBE" = "true" ]; then
  echo "-- Minikube status"
  minikube status -p "$K8SCLUSTER" >/dev/null
fi
"""

[infra-status]
description = "Show minikube cluster status"
wait_for = ["infra-start"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

if [ "$MINIKUBE" = "true" ]; then
  echo "-- Minikube status"
  minikube status -p "$K8SCLUSTER"
else
  echo "This operation is for minikube driver only!"
fi
"""

[infra-info]
description = "Show cluster info and grafana credentials"
wait_for = ["infra-start", "infra-grafana-port-forward-start", "cnpg-cluster-update"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
INSTALL_PROMETHEUS="${INSTALL_PROMETHEUS:-{{vars.INSTALL_PROMETHEUS}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"
GRAFANA_PORT="${GRAFANA_PORT:-{{vars.GRAFANA_PORT}}}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

echo
echo "You can now set your env:"
echo "  export KUBECONFIG=\"${KUBECONFIG}\""

if [ "$INSTALL_PROMETHEUS" = "true" ] && [ "$MINIKUBE" = "true" ]; then
  grafana_user=$(kubectl get secret -n monitoring prometheus-community-grafana \
    -o jsonpath='{.data.admin-user}' | base64 -d)
  grafana_pass=$(kubectl get secret -n monitoring prometheus-community-grafana \
    -o jsonpath='{.data.admin-password}' | base64 -d)
  echo "-- grafana credentials:"
  echo "  ${grafana_user} // ${grafana_pass}"
  echo "  grafana URL: http://localhost:${GRAFANA_PORT}/d/cloudnative-pg/cloudnativepg?orgId=1&refresh=30s"
fi
"""

[infra-delete-cluster]
description = "Delete the minikube cluster"
depends = ["infra-stop"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
POSTGRESQL_INSTANCE="${POSTGRESQL_INSTANCE:-{{vars.POSTGRESQL_INSTANCE}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"

MINIKUBE_PERSISTENT_PATH="${PWD}/persistentVolumesData/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

if [ "$MINIKUBE" = "true" ]; then
  echo "-- Deleting Minikube cluster"
  minikube delete -p "$K8SCLUSTER" || true
fi
"""

[infra-delete-profile]
description = "Delete the cluster and all generated files for this profile"
depends = ["infra-delete-cluster"]
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
POSTGRESQL_INSTANCE="${POSTGRESQL_INSTANCE:-{{vars.POSTGRESQL_INSTANCE}}}"

GENERATED_K8S_PATH="generated/k8s/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
GENERATED_HELM_VALUES_PATH="generated/helm-values/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
GENERATED_CFG_PATH="generated/cfg/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"
MINIKUBE_PERSISTENT_PATH="${PWD}/persistentVolumesData/${K8SCLUSTER}.d/${POSTGRESQL_INSTANCE}"

rm -f "${GENERATED_K8S_PATH}/"*.yml
rmdir "${GENERATED_K8S_PATH}" 2>/dev/null || true

rm -f "${GENERATED_HELM_VALUES_PATH}/"*.yml
rmdir "${GENERATED_HELM_VALUES_PATH}" 2>/dev/null || true

rm -f "${GENERATED_CFG_PATH}/"*.yml
rmdir "${GENERATED_CFG_PATH}" 2>/dev/null || true

rm -rf "$MINIKUBE_PERSISTENT_PATH"
"""

[infra-dashboard]
description = "Launch Minikube dashboard"
run = """
#!/usr/bin/env bash
set -euo pipefail

K8SCLUSTER="${K8SCLUSTER:-{{vars.K8SCLUSTER}}}"
MINIKUBE="${MINIKUBE:-{{vars.MINIKUBE}}}"

export KUBECONFIG="${PWD}/generated/k8s/${K8SCLUSTER}.kubeconfig"

if [ "$MINIKUBE" = "true" ]; then
  echo "-- Launching Minikube dashboard"
  minikube dashboard -p "$K8SCLUSTER"
else
  echo "This operation is for minikube driver only!"
fi
"""
