---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /tmp/hostpath_pv_data/postgresql_data